export const Continents = [
    {
        continent: 'Africa',
        countries:[
        {name: 'Djibouti', flag: 'https://flagcdn.com/w320/dj.png'},
        {name: 'Mali', flag: 'https://flagcdn.com/w320/ml.png'},
        {name: 'Comoros', flag: 'https://flagcdn.com/w320/km.png'},
        {name: 'Namibia', flag: 'https://flagcdn.com/w320/na.png'},
        {name: 'Republic of the Congo', flag: 'https://flagcdn.com/w320/cg.png'},
        {name: 'Gambia', flag: 'https://flagcdn.com/w320/gm.png'},
        {name: 'Tunisia', flag: 'https://flagcdn.com/w320/tn.png'},
        {name: 'Cameroon', flag: 'https://flagcdn.com/w320/cm.png'},
        {name: 'Chad', flag: 'https://flagcdn.com/w320/td.png'},
        {name: 'Algeria', flag: 'https://flagcdn.com/w320/dz.png'},
        {name: 'Guinea', flag: 'https://flagcdn.com/w320/gn.png'},
        {name: 'Mayotte', flag: 'https://flagcdn.com/w320/yt.png'},
        {name: 'Rwanda', flag: 'https://flagcdn.com/w320/rw.png'},
        {name: 'Morocco', flag: 'https://flagcdn.com/w320/ma.png'},
        {name: 'Benin', flag: 'https://flagcdn.com/w320/bj.png'},
        {name: 'Mauritius', flag: 'https://flagcdn.com/w320/mu.png'},
        {name: 'Mauritania', flag: 'https://flagcdn.com/w320/mr.png'},
        {name: 'Malawi', flag: 'https://flagcdn.com/w320/mw.png'},
        {name: 'Ivory Coast', flag: 'https://flagcdn.com/w320/ci.png'},
        {name: 'Liberia', flag: 'https://flagcdn.com/w320/lr.png'},
        {name: 'Egypt', flag: 'https://flagcdn.com/w320/eg.png'},
        {name: 'Zimbabwe', flag: 'https://flagcdn.com/w320/zw.png'},
        {name: 'Senegal', flag: 'https://flagcdn.com/w320/sn.png'},
        {name: 'Lesotho', flag: 'https://flagcdn.com/w320/ls.png'},
        {name: 'Tanzania', flag: 'https://flagcdn.com/w320/tz.png'},
        {name: 'Togo', flag: 'https://flagcdn.com/w320/tg.png'},
        {name: 'Cape Verde', flag: 'https://flagcdn.com/w320/cv.png'},
        {name: 'South Sudan', flag: 'https://flagcdn.com/w320/ss.png'},
        {name: 'Saint Helena, Ascension and Tristan da Cunha', flag: 'https://flagcdn.com/w320/sh.png'},
        {name: 'Ethiopia', flag: 'https://flagcdn.com/w320/et.png'},
        {name: 'Niger', flag: 'https://flagcdn.com/w320/ne.png'},
        {name: 'Eritrea', flag: 'https://flagcdn.com/w320/er.png'},
        {name: 'Sierra Leone', flag: 'https://flagcdn.com/w320/sl.png'},
        {name: 'Mozambique', flag: 'https://flagcdn.com/w320/mz.png'},
        {name: 'Réunion', flag: 'https://flagcdn.com/w320/re.png'},
        {name: 'Central African Republic', flag: 'https://flagcdn.com/w320/cf.png'},
        {name: 'Libya', flag: 'https://flagcdn.com/w320/ly.png'},
        {name: 'Guinea-Bissau', flag: 'https://flagcdn.com/w320/gw.png'},
        {name: 'Botswana', flag: 'https://flagcdn.com/w320/bw.png'},
        {name: 'DR Congo', flag: 'https://flagcdn.com/w320/cd.png'},
        {name: 'Nigeria', flag: 'https://flagcdn.com/w320/ng.png'}
        ]
    }
]